version: "3.2"
services:
  db:
    image: mongo
  app:
    depends_on:
      - "db"
    environment:
      - MONGO_URI=mongodb://db:27017/pimex-core
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
